services:
    app:
        container_name: "voluptuaria-api"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:3000"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
        command: nodemon --legacy-watch --ignore **/dist/* --ext ts,json,.env --exec "npm run start -- --unbuffered"
        depends_on:
            - database
    database:
        image: mysql:8.0.33
        container_name: "voluptuaria-database"
        environment:
            MYSQL_ROOT_PASSWORD: "motdepasse"
            MYSQL_DATABASE: "voluptuaria"
            MYSQL_PASSWORD: "motdepasse"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        restart: always
volumes:
    db_data:
