version: '3.8'

services:
  app:
    container_name: voluptuaria-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=""
      - DB_NAME=voluptuaria_database
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  mysql:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: voluptuaria_database
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: