name: Code Quality Checks

on:
  push:
    branches: [api]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd api/voluptuaria-api
          npm install --save-dev

      - name: Run Prettier to format files
        run: |
          cd api/voluptuaria-api
          npm run prettier:format

      - name: Amend the commit with Prettier changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --amend --no-edit

      - name: Force-push the changes
        run: |
          git push origin ${{ github.ref }} --force-with-lease  # Force push the amended commit
